# Generated by Django 4.0.3 on 2022-04-02 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallerie_s', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('favourite', models.ManyToManyField(related_name='Galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('sign', models.CharField(max_length=100, verbose_name='Sign')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('private', models.BooleanField(default=False, verbose_name='Private')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_s', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('favourite', models.ManyToManyField(related_name='images', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.gallery')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
    ]
